services:

  backend:
    build:
      context: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    dns:
      - 10.0.0.2
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
